// This file was autogenerated from ATmega328.conf. Do not edit manually!

// timer0_mode

inline void timer0_mode_normal()
{
	TCCR0B &= ~(1<<WGM02);
	TCCR0A &= ~(1<<WGM01);
	TCCR0A &= ~(1<<WGM00);
}

inline void timer0_mode_pwm_phasecorrect_until_0xFF()
{
	TCCR0B &= ~(1<<WGM02);
	TCCR0A &= ~(1<<WGM01);
	TCCR0A |=  (1<<WGM00);
}

inline void timer0_mode_ctc()
{
	TCCR0B &= ~(1<<WGM02);
	TCCR0A |=  (1<<WGM01);
	TCCR0A &= ~(1<<WGM00);
}

inline void timer0_mode_fast_pwm_until_0xFF()
{
	TCCR0B &= ~(1<<WGM02);
	TCCR0A |=  (1<<WGM01);
	TCCR0A |=  (1<<WGM00);
}

inline void timer0_mode_pwm_phasecorrect_until_OCR0A()
{
	TCCR0B |=  (1<<WGM02);
	TCCR0A &= ~(1<<WGM01);
	TCCR0A |=  (1<<WGM00);
}

inline void timer0_mode_fast_pwm_until_OCR0A()
{
	TCCR0B |=  (1<<WGM02);
	TCCR0A |=  (1<<WGM01);
	TCCR0A |=  (1<<WGM00);
}

// timer0_clockselect

inline void timer0_clockselect_none()
{
	TCCR0B &= ~(1<<CS02);
	TCCR0B &= ~(1<<CS01);
	TCCR0B &= ~(1<<CS00);
}

inline void timer0_clockselect_io_1()
{
	TCCR0B &= ~(1<<CS02);
	TCCR0B &= ~(1<<CS01);
	TCCR0B |=  (1<<CS00);
}

inline void timer0_clockselect_io_8()
{
	TCCR0B &= ~(1<<CS02);
	TCCR0B |=  (1<<CS01);
	TCCR0B &= ~(1<<CS00);
}

inline void timer0_clockselect_io_64()
{
	TCCR0B &= ~(1<<CS02);
	TCCR0B |=  (1<<CS01);
	TCCR0B |=  (1<<CS00);
}

inline void timer0_clockselect_io_256()
{
	TCCR0B |=  (1<<CS02);
	TCCR0B &= ~(1<<CS01);
	TCCR0B &= ~(1<<CS00);
}

inline void timer0_clockselect_io_1024()
{
	TCCR0B |=  (1<<CS02);
	TCCR0B &= ~(1<<CS01);
	TCCR0B |=  (1<<CS00);
}

inline void timer0_clockselect_on_falling_T0()
{
	TCCR0B |=  (1<<CS02);
	TCCR0B |=  (1<<CS01);
	TCCR0B &= ~(1<<CS00);
}

inline void timer0_clockselect_on_rising_T0()
{
	TCCR0B |=  (1<<CS02);
	TCCR0B |=  (1<<CS01);
	TCCR0B |=  (1<<CS00);
}

// timer1_mode

inline void timer1_mode_normal()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A &= ~(1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_phasecorrect_until_0x00FF()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A &= ~(1<<WGM11);
	TCCR1A |=  (1<<WGM10);
}

inline void timer1_mode_pwm_phasecorrect_until_0x01FF()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_phasecorrect_until_0x03FF()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A |=  (1<<WGM10);
}

inline void timer1_mode_ctc_until_OCR1A()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B |=  (1<<WGM12);
	TCCR1A &= ~(1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_fast_until_0x00FF()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B |=  (1<<WGM12);
	TCCR1A &= ~(1<<WGM11);
	TCCR1A |=  (1<<WGM10);
}

inline void timer1_mode_pwm_fast_until_0x01FF()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B |=  (1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_fast_until_0x03FF()
{
	TCCR1B &= ~(1<<WGM13);
	TCCR1B |=  (1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A |=  (1<<WGM10);
}

inline void timer1_mode_pwm_phasefrequencycorrect_until_ICR1()
{
	TCCR1B |=  (1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A &= ~(1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_phasefrequencycorrect_until_OCR1A()
{
	TCCR1B |=  (1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A &= ~(1<<WGM11);
	TCCR1A |=  (1<<WGM10);
}

inline void timer1_mode_pwm_phasecorrect_until_ICR1()
{
	TCCR1B |=  (1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_phasecorrect_until_OCR1A()
{
	TCCR1B |=  (1<<WGM13);
	TCCR1B &= ~(1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A |=  (1<<WGM10);
}

inline void timer1_mode_ctc_until_ICR1()
{
	TCCR1B |=  (1<<WGM13);
	TCCR1B |=  (1<<WGM12);
	TCCR1A &= ~(1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_fast_until_ICR1()
{
	TCCR1B |=  (1<<WGM13);
	TCCR1B |=  (1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A &= ~(1<<WGM10);
}

inline void timer1_mode_pwm_fast_until_OCR1A()
{
	TCCR1B |=  (1<<WGM13);
	TCCR1B |=  (1<<WGM12);
	TCCR1A |=  (1<<WGM11);
	TCCR1A |=  (1<<WGM10);
}

// timer1_clockselect

inline void timer1_clockselect_none()
{
	TCCR1B &= ~(1<<CS12);
	TCCR1B &= ~(1<<CS11);
	TCCR1B &= ~(1<<CS10);
}

inline void timer1_clockselect_io_1()
{
	TCCR1B &= ~(1<<CS12);
	TCCR1B &= ~(1<<CS11);
	TCCR1B |=  (1<<CS10);
}

inline void timer1_clockselect_io_8()
{
	TCCR1B &= ~(1<<CS12);
	TCCR1B |=  (1<<CS11);
	TCCR1B &= ~(1<<CS10);
}

inline void timer1_clockselect_io_64()
{
	TCCR1B &= ~(1<<CS12);
	TCCR1B |=  (1<<CS11);
	TCCR1B |=  (1<<CS10);
}

inline void timer1_clockselect_io_256()
{
	TCCR1B |=  (1<<CS12);
	TCCR1B &= ~(1<<CS11);
	TCCR1B &= ~(1<<CS10);
}

inline void timer1_clockselect_io_1024()
{
	TCCR1B |=  (1<<CS12);
	TCCR1B &= ~(1<<CS11);
	TCCR1B |=  (1<<CS10);
}

inline void timer1_clockselect_on_falling_T1()
{
	TCCR1B |=  (1<<CS12);
	TCCR1B |=  (1<<CS11);
	TCCR1B &= ~(1<<CS10);
}

inline void timer1_clockselect_on_rising_T1()
{
	TCCR1B |=  (1<<CS12);
	TCCR1B |=  (1<<CS11);
	TCCR1B |=  (1<<CS10);
}

// timer2_mode

inline void timer2_mode_normal()
{
	TCCR2B &= ~(1<<WGM22);
	TCCR2A &= ~(1<<WGM21);
	TCCR2A &= ~(1<<WGM20);
}

inline void timer2_mode_pwm_phasecorrect_until_0xFF()
{
	TCCR2B &= ~(1<<WGM22);
	TCCR2A &= ~(1<<WGM21);
	TCCR2A |=  (1<<WGM20);
}

inline void timer2_mode_ctc_until_OCR2A()
{
	TCCR2B &= ~(1<<WGM22);
	TCCR2A |=  (1<<WGM21);
	TCCR2A &= ~(1<<WGM20);
}

inline void timer2_mode_pwm_fast_until_0xFF()
{
	TCCR2B &= ~(1<<WGM22);
	TCCR2A |=  (1<<WGM21);
	TCCR2A |=  (1<<WGM20);
}

inline void timer2_mode_pwm_phasecorrect_until_OCR2A()
{
	TCCR2B |=  (1<<WGM22);
	TCCR2A &= ~(1<<WGM21);
	TCCR2A |=  (1<<WGM20);
}

inline void timer2_mode_pwm_fast_until_OCR2A()
{
	TCCR2B |=  (1<<WGM22);
	TCCR2A |=  (1<<WGM21);
	TCCR2A |=  (1<<WGM20);
}

// timer2_clockselect

inline void timer2_clockselect_none()
{
	TCCR2B &= ~(1<<CS22);
	TCCR2B &= ~(1<<CS21);
	TCCR2B &= ~(1<<CS20);
}

inline void timer2_clockselect_t2clk_1()
{
	TCCR2B &= ~(1<<CS22);
	TCCR2B &= ~(1<<CS21);
	TCCR2B |=  (1<<CS20);
}

inline void timer2_clockselect_t2clk_8()
{
	TCCR2B &= ~(1<<CS22);
	TCCR2B |=  (1<<CS21);
	TCCR2B &= ~(1<<CS20);
}

inline void timer2_clockselect_t2clk_32()
{
	TCCR2B &= ~(1<<CS22);
	TCCR2B |=  (1<<CS21);
	TCCR2B |=  (1<<CS20);
}

inline void timer2_clockselect_t2clk_64()
{
	TCCR2B |=  (1<<CS22);
	TCCR2B &= ~(1<<CS21);
	TCCR2B &= ~(1<<CS20);
}

inline void timer2_clockselect_t2clk_128()
{
	TCCR2B |=  (1<<CS22);
	TCCR2B &= ~(1<<CS21);
	TCCR2B |=  (1<<CS20);
}

inline void timer2_clockselect_t2clk_256()
{
	TCCR2B |=  (1<<CS22);
	TCCR2B |=  (1<<CS21);
	TCCR2B &= ~(1<<CS20);
}

inline void timer2_clockselect_t2clk_1024()
{
	TCCR2B |=  (1<<CS22);
	TCCR2B |=  (1<<CS21);
	TCCR2B |=  (1<<CS20);
}

// spi0_enable

inline void spi0_enable_disable()
{
	SPCR0 &= ~(1<<SPE0);
}

inline void spi0_enable_enable()
{
	SPCR0 |=  (1<<SPE0);
}

// spi0_mode

inline void spi0_mode_slave()
{
	SPCR0 &= ~(1<<MSTR0);
}

inline void spi0_mode_master()
{
	SPCR0 |=  (1<<MSTR0);
}

// spi0_polarity

inline void spi0_polarity_leading_rising()
{
	SPCR0 &= ~(1<<CPOL0);
}

inline void spi0_polarity_leading_falling()
{
	SPCR0 |=  (1<<CPOL0);
}

// spi0_phase

inline void spi0_phase_leading_sample()
{
	SPCR0 &= ~(1<<CPHA0);
}

inline void spi0_phase_leading_setup()
{
	SPCR0 |=  (1<<CPHA0);
}

// spi0_clock

inline void spi0_clock_fosc_4()
{
	SPSR0 &= ~(1<<SPI2X0);
	SPCR0 &= ~(1<<SPR01);
	SPCR0 &= ~(1<<SPR00);
}

inline void spi0_clock_fosc_16()
{
	SPSR0 &= ~(1<<SPI2X0);
	SPCR0 &= ~(1<<SPR01);
	SPCR0 |=  (1<<SPR00);
}

inline void spi0_clock_fosc_64()
{
	SPSR0 &= ~(1<<SPI2X0);
	SPCR0 |=  (1<<SPR01);
	SPCR0 &= ~(1<<SPR00);
}

inline void spi0_clock_fosc_128()
{
	SPSR0 &= ~(1<<SPI2X0);
	SPCR0 |=  (1<<SPR01);
	SPCR0 |=  (1<<SPR00);
}

inline void spi0_clock_fosc_2()
{
	SPSR0 |=  (1<<SPI2X0);
	SPCR0 &= ~(1<<SPR01);
	SPCR0 &= ~(1<<SPR00);
}

inline void spi0_clock_fosc_8()
{
	SPSR0 |=  (1<<SPI2X0);
	SPCR0 &= ~(1<<SPR01);
	SPCR0 |=  (1<<SPR00);
}

inline void spi0_clock_fosc_32()
{
	SPSR0 |=  (1<<SPI2X0);
	SPCR0 |=  (1<<SPR01);
	SPCR0 &= ~(1<<SPR00);
}

inline void spi0_clock_fosc_64()
{
	SPSR0 |=  (1<<SPI2X0);
	SPCR0 |=  (1<<SPR01);
	SPCR0 |=  (1<<SPR00);
}

// interrupts


inline void int_timer0_compA_enable()
{
	TIMSK0 |=  (1<<OCIE0A);
}

inline void int_timer0_compA_disable()
{
	TIMSK0 &= ~(1<<OCIE0A);
}

inline void int_timer0_compB_enable()
{
	TIMSK0 |=  (1<<OCIE0B);
}

inline void int_timer0_compB_disable()
{
	TIMSK0 &= ~(1<<OCIE0B);
}

inline void int_timer0_overflow_enable()
{
	TIMSK0 |=  (1<<TOIE0);
}

inline void int_timer0_overflow_disable()
{
	TIMSK0 &= ~(1<<TOIE0);
}

inline void int_timer1_input_capture_enable()
{
	TIMSK1 |=  (1<<ICIE1);
}

inline void int_timer1_input_capture_disable()
{
	TIMSK1 &= ~(1<<ICIE1);
}

inline void int_timer1_compA_enable()
{
	TIMSK1 |=  (1<<OCIE1A);
}

inline void int_timer1_compA_disable()
{
	TIMSK1 &= ~(1<<OCIE1A);
}

inline void int_timer1_compB_enable()
{
	TIMSK1 |=  (1<<OCIE1B);
}

inline void int_timer1_compB_disable()
{
	TIMSK1 &= ~(1<<OCIE1B);
}

inline void int_timer1_overflow_enable()
{
	TIMSK1 |=  (1<<TOIE1);
}

inline void int_timer1_overflow_disable()
{
	TIMSK1 &= ~(1<<TOIE1);
}

inline void int_spi0_enable()
{
	SPCR0 |=  (1<<SPIE0);
}

inline void int_spi0_disable()
{
	SPCR0 &= ~(1<<SPIE0);
}
